kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - alpha
    - beta
    - rc
  event:
    - push

steps:
  - name: install
    image: node:16-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:16-alpine
    commands:
      - yarn run lint:check

  - name: docs
    image: node:16-alpine
    commands:
      - yarn docs:toc

  - name: build
    image: node:16-alpine
    commands:
      - yarn run build

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      git_method: gh
      add_modules:
        - '@qiwi/multi-semantic-release'
      override: multi-semantic-release
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      npm_token:
        from_secret: npm_token
    when:
      branch:
        - master
        - alpha
        - beta
        - rc
      event:
        - push

  - name: inform
    image: drillster/drone-email
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from:
        from_secret: smtp_username
    when:
      status:
        - changed
        - failure

image_pull_secrets:
  - dockerconfigjson
