stages:
  - install
  - build
  - docs
  - publish

variables:
  NODE_VERSION: 20-alpine
  SEMANTIC_RELEASE_WORKSPACE: 'true'

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
