version: "3.7"
services:
  monorepo:
    image: cenk1cenk2/lerna-dev:latest
    environment:
      - SERVICES=packages/nestjs-utils:packages/nestjs-transactions:packages/nestjs-utils
      # - RUN_IN_BAND=packages/nestjs-utils
    volumes:
      - .:/data/app
