version: '3.7'
services:
  monorepo:
    image: cenk1cenk2/node-fnm:latest
    environment:
      SYNC_WAIT: 15
      PROXY_PACKAGES_FOLDER: packages
      SERVICE_0_CWD: packages/nestjs-utils
      SERVICE_0_NAME: nestjs-utils
      SERVICE_0_SYNC: 'true'
      SERVICE_1_CWD: packages/nestjs-auth-key-generator
      SERVICE_1_NAME: nestjs-auth-key-generator
      SERVICE_2_CWD: packages/nestjs-emitter
      SERVICE_2_NAME: nestjs-emitter
      SERVICE_3_CWD: packages/nestjs-graphql
      SERVICE_3_NAME: nestjs-graphql
      SERVICE_4_CWD: packages/nestjs-graphql-generator
      SERVICE_4_NAME: nestjs-graphql-generator
      SERVICE_5_CWD: packages/nestjs-transactions
      SERVICE_5_NAME: nestjs-transactions
      SERVICE_6_CWD: packages/nestjs-typeorm
      SERVICE_6_NAME: nestjs-typeorm
    volumes:
      - .:/data
